
// This file has been generated by the GUI designer. Do not modify.
namespace shedule_parser
{
	public partial class Shedule
	{
		private global::Gtk.Alignment alignment1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget shedule_parser.Shedule
			this.Name = "shedule_parser.Shedule";
			this.Title = global::Mono.Unix.Catalog.GetString("Расписание");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child shedule_parser.Shedule.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.GtkScrolledWindow.Add(this.textview1);
			this.alignment1.Add(this.GtkScrolledWindow);
			this.Add(this.alignment1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 272;
			this.Show();
		}
	}
}
